from __future__ import annotations
from typing import Optional
from fastapi import APIRouter
from models import ChatRequest, ChatResponse
from services import p2_session, p3_episodic, p4_knowledge, p5_translation
import context_assembler
from openai import OpenAI
from config import settings

router = APIRouter(prefix="/chat", tags=["chat"])
_llm = OpenAI(
    api_key=settings.openrouter_api_key,
    base_url="https://openrouter.ai/api/v1",
)


@router.post("", response_model=ChatResponse)
async def chat(req: ChatRequest):
    # Ensure session exists
    session = p2_session.get_session(req.session_id)
    if not session:
        req.session_id = p2_session.create_session(req.user_id, req.brand_id, req.market)
    else:
        p2_session.update_context(req.session_id, req.brand_id, req.market)

    # Extract & store any facts from this message (P3 write path)
    stored_facts = p3_episodic.extract_and_store_facts(
        req.message, req.user_id, req.brand_id, req.market, _llm
    )

    # Assemble context from all 5 tiers
    system_prompt, memory_trace, is_blocked = context_assembler.assemble(
        message=req.message,
        session_id=req.session_id,
        user_id=req.user_id,
        brand_id=req.brand_id,
        market=req.market,
        target_language=req.target_language,
    )

    if is_blocked:
        violations = memory_trace["P1"].get("violations", [])
        block_msg = "⛔ Response blocked by compliance guardrail (P1).\n\n"
        for v in violations:
            block_msg += f"**Rule violated:** {v['name']}\n{v['message']}\n\n"
        block_msg += "_This type of content cannot be generated by Brain OS per pharma compliance policy._"

        p2_session.add_turn(req.session_id, "user", req.message)
        p2_session.add_turn(req.session_id, "assistant", "[BLOCKED BY P1 GUARDRAIL]")
        return ChatResponse(
            response=block_msg,
            blocked=True,
            session_id=req.session_id,
            memory_trace=memory_trace,
            context_summary=_make_summary(memory_trace, stored_facts),
        )

    # Get conversation history for multi-turn
    turns = p2_session.get_conversation_turns(req.session_id)
    messages = turns[-6:] + [{"role": "user", "content": req.message}]

    # Call LLM
    response = _llm.chat.completions.create(
        model=settings.llm_model,
        max_tokens=settings.max_tokens,
        messages=[{"role": "system", "content": system_prompt}] + messages,
    )
    answer = response.choices[0].message.content

    # Store turns in P2 session memory
    p2_session.add_turn(req.session_id, "user", req.message)
    p2_session.add_turn(req.session_id, "assistant", answer)

    # Update memory_trace with stored facts info
    if stored_facts:
        memory_trace["P3"]["stored_facts"] = stored_facts

    return ChatResponse(
        response=answer,
        blocked=False,
        session_id=req.session_id,
        memory_trace=memory_trace,
        context_summary=_make_summary(memory_trace, stored_facts),
    )


@router.post("/session")
async def create_session(user_id: str, brand_id: Optional[str] = None, market: Optional[str] = None):
    session_id = p2_session.create_session(user_id, brand_id, market)
    return {"session_id": session_id, "user_id": user_id, "brand_id": brand_id, "market": market}


@router.get("/sessions/{user_id}")
async def list_sessions(user_id: str):
    return p2_session.list_sessions(user_id)


def _make_summary(trace: dict, stored_facts: list) -> dict:
    active_tiers = [k for k in ["P1", "P2", "P3", "P4", "P5"] if trace.get(k, {}).get("hit")]
    return {
        "active_tiers": active_tiers,
        "total_tokens": trace.get("total_tokens", 0),
        "new_memories_stored": len(stored_facts),
        "stored_facts": stored_facts,
    }
